Restaurant.destroy_all
OnionRing.destroy_all
Review.destroy_all
User.destroy_all

@res1 = Restaurant.create(name: "Bernhard Group", address: "1010 West Houston", phone_number: "786-001-5555", img_path: "/assets/res_01.png")
@res2 = Restaurant.create(name: "Blanda LCC", address: "2020 West Houston", phone_number: "786-002-5555", img_path: "/assets/res_02.png")
@res3 = Restaurant.create(name: "Weimann-Torphy", address: "3030 West Houston", phone_number: "786-003-5555", img_path: "/assets/res_03.png")
@res4 = Restaurant.create(name: "Daugherty, Mills and Johnston", address: "4040 West Houston", phone_number: "786-004-5555", img_path: "/assets/res_04.png")
@res5 = Restaurant.create(name: "Sporer, Stracke and Gutmann", address: "5050 West Houston", phone_number: "786-005-5555", img_path: "/assets/res_05.png")
@res6 = Restaurant.create(name: "Toy-Murazik", address: "6060 West Houston", phone_number: "786-006-5555", img_path: "/assets/res_06.png")
@res7 = Restaurant.create(name: "Kessler-Zemlak", address: "7070 West Houston", phone_number: "786-007-5555", img_path: "/assets/res_07.png")
@res8 = Restaurant.create(name: "Hirthe Inc", address: "8080 West Houston", phone_number: "786-008-5555", img_path: "/assets/res_08.png")
@res9 = Restaurant.create(name: "Monahan-Heany", address: "9090 West Houston", phone_number: "786-009-5555", img_path: "/assets/res_09.png")
@res10 = Restaurant.create(name: "Williamson-Barrows", address: "1111 West Houston", phone_number: "786-010-5555", img_path: "/assets/res_10.png")

@onion1 = OnionRing.create(name: "Skinny Onions", nutritional_facts: "Very skinny. 100 Calories", img_path: "/assets/onion_01.jpg")
@onion2 = OnionRing.create(name: "Red Spicy Onion", nutritional_facts: "Very spicy. 200 Calories", img_path: "/assets/onion_02.jpg")
@onion3 = OnionRing.create(name: "Orange Onions", nutritional_facts: "Very orange. 300 Calories", img_path: "/assets/onion_03.jpg")
@onion4 = OnionRing.create(name: "Orange and Red Onions", nutritional_facts: "Very orange, but also red. 400 Calories", img_path: "/assets/onion_04.jpg")
@onion5 = OnionRing.create(name: "Yellow Onions", nutritional_facts: "Very yellow. 500 Calories", img_path: "/assets/onion_05.jpg")
@onion6 = OnionRing.create(name: "Pink Onions", nutritional_facts: "Very pink. 600 Calories", img_path: "/assets/onion_06.jpg")
@onion7 = OnionRing.create(name: "Crunchy Bluw Onions", nutritional_facts: "Very crunchy, not so blue. 100 Calories", img_path: "/assets/onion_07.jpeg")
@onion8 = OnionRing.create(name: "Burger Onions", nutritional_facts: "Very delicious. 100 Calories", img_path: "/assets/onion_08.jpg")
@onion9 = OnionRing.create(name: "Flower Onions", nutritional_facts: "Looks like a flower. 100 Calories", img_path: "/assets/onion_09.jpeg")
@onion10 = OnionRing.create(name: "Mustard Onions", nutritional_facts: "50% mustard, %50 onion. 100 Calories", img_path: "/assets/onion_10.jpg")
@onion11 = OnionRing.create(name: "Pixel Onions", nutritional_facts: "Only eatable if you are a video game character. 100 Calories", img_path: "/assets/onion_11.jpg")
@onion12 = OnionRing.create(name: "Almond Onions", nutritional_facts: "Very healthy. 100 Calories", img_path: "/assets/onion_12.jpg")
@onion13 = OnionRing.create(name: "Tomato Onions", nutritional_facts: "Roman tomatoes with onions. 100 Calories", img_path: "/assets/onion_13.jpg")
@onion14 = OnionRing.create(name: "Fish Onions", nutritional_facts: "Fish with onions. 100 Calories", img_path: "/assets/onion_14.jpg")
@onion15 = OnionRing.create(name: "Shrimp and Lemon Onions", nutritional_facts: "Very shrimpy, not so lemony. 100 Calories", img_path: "/assets/onion_15.jpg")
@onion16 = OnionRing.create(name: "Soft Onions", nutritional_facts: "Very soft. 100 Calories", img_path: "/assets/onion_16.jpg")
@onion17 = OnionRing.create(name: "Egg Salad Onions", nutritional_facts: "Very eggy. 100 Calories", img_path: "/assets/onion_17.jpg")
@onion18 = OnionRing.create(name: "Original Shrimp Onions", nutritional_facts: "Very original. 100 Calories", img_path: "/assets/onion_18.jpg")
@onion19 = OnionRing.create(name: "Secret Sauce Onions", nutritional_facts: "Very secret. 100 Calories", img_path: "/assets/onion_19.jpg")
@onion20 = OnionRing.create(name: "Beer Oions", nutritional_facts: "Cooked on beer. 100 Calories", img_path: "/assets/onion_20.jpg")
@onion21 = OnionRing.create(name: "Garlic Onions", nutritional_facts: "A lot of garlic. 100 Calories", img_path: "/assets/onion_21.jpg")
@onion22 = OnionRing.create(name: "Salty Onions", nutritional_facts: "Very salty. 100 Calories", img_path: "/assets/onion_22.jpg")

@onion_res01 = OnionRestaurant.create(restaurant_id: @res1.id, onion_ring_id: @onion1.id)
@onion_res02 = OnionRestaurant.create(restaurant_id: @res1.id, onion_ring_id: @onion2.id)
@onion_res03 = OnionRestaurant.create(restaurant_id: @res1.id, onion_ring_id: @onion3.id)
@onion_res04 = OnionRestaurant.create(restaurant_id: @res2.id, onion_ring_id: @onion4.id)
@onion_res05 = OnionRestaurant.create(restaurant_id: @res2.id, onion_ring_id: @onion5.id)
@onion_res06 = OnionRestaurant.create(restaurant_id: @res2.id, onion_ring_id: @onion6.id)
@onion_res07 = OnionRestaurant.create(restaurant_id: @res3.id, onion_ring_id: @onion7.id)
@onion_res08 = OnionRestaurant.create(restaurant_id: @res3.id, onion_ring_id: @onion8.id)
@onion_res09 = OnionRestaurant.create(restaurant_id: @res3.id, onion_ring_id: @onion9.id)
@onion_res10 = OnionRestaurant.create(restaurant_id: @res4.id, onion_ring_id: @onion10.id)
@onion_res11 = OnionRestaurant.create(restaurant_id: @res4.id, onion_ring_id: @onion11.id)
@onion_res12 = OnionRestaurant.create(restaurant_id: @res4.id, onion_ring_id: @onion12.id)
@onion_res13 = OnionRestaurant.create(restaurant_id: @res5.id, onion_ring_id: @onion13.id)
@onion_res14 = OnionRestaurant.create(restaurant_id: @res5.id, onion_ring_id: @onion14.id)
@onion_res15 = OnionRestaurant.create(restaurant_id: @res5.id, onion_ring_id: @onion15.id)
@onion_res16 = OnionRestaurant.create(restaurant_id: @res6.id, onion_ring_id: @onion16.id)
@onion_res17 = OnionRestaurant.create(restaurant_id: @res6.id, onion_ring_id: @onion17.id)
@onion_res18 = OnionRestaurant.create(restaurant_id: @res6.id, onion_ring_id: @onion18.id)
@onion_res19 = OnionRestaurant.create(restaurant_id: @res7.id, onion_ring_id: @onion19.id)
@onion_res20 = OnionRestaurant.create(restaurant_id: @res7.id, onion_ring_id: @onion20.id)
@onion_res21 = OnionRestaurant.create(restaurant_id: @res7.id, onion_ring_id: @onion21.id)
@onion_res22 = OnionRestaurant.create(restaurant_id: @res8.id, onion_ring_id: @onion22.id)
@onion_res23 = OnionRestaurant.create(restaurant_id: @res8.id, onion_ring_id: @onion1.id)
@onion_res24 = OnionRestaurant.create(restaurant_id: @res8.id, onion_ring_id: @onion2.id)
@onion_res25 = OnionRestaurant.create(restaurant_id: @res9.id, onion_ring_id: @onion3.id)
@onion_res26 = OnionRestaurant.create(restaurant_id: @res9.id, onion_ring_id: @onion4.id)
@onion_res27 = OnionRestaurant.create(restaurant_id: @res9.id, onion_ring_id: @onion5.id)
@onion_res28 = OnionRestaurant.create(restaurant_id: @res10.id, onion_ring_id: @onion6.id)
@onion_res29 = OnionRestaurant.create(restaurant_id: @res10.id, onion_ring_id: @onion7.id)
@onion_res30 = OnionRestaurant.create(restaurant_id: @res10.id, onion_ring_id: @onion8.id)